export const sample_articles = [
    {
        id: '1',
        name: 'Red Dress',
        price: 250,
        favorite: false,
        stars: 4.5,
        imageUrl: 'clothes1.jpg',
        tags: ['Clothes'],
    },
    {
        id: '2',
        name: 'Djeba for men',
        price: 520,
        favorite: true,
        stars: 5,
        imageUrl: 'clothes2.jpg',
        tags: ['Clothes'],
    },

    {
        id: '3',
        name: 'Amazighian Dress',
        price: 780,
        favorite: false,
        stars: 4,
        imageUrl: 'clothes3.jpg',
        tags: ['Clothes'],
    },
    {
        id: '4',
        name: 'Pink Dress',
        price: 820,
        favorite: false,
        stars: 4.5,
        imageUrl: 'clothes4.jpg',
        tags: ['Clothes'],
    },
    {
        id: '5',
        name: 'Neckless with Fatma Hand',
        price: 1800,
        favorite: false,
        stars: 4.5,
        imageUrl: 'accessory1.jpg',
        tags: ['Accessories'],
    },

    {
        id: '6',
        name: 'Neckless of Moknin',
        price: 2400,
        favorite: false,
        stars: 5,
        imageUrl: 'accessory2.jpg',
        tags: ['Accessories'],
    },
    {
        id: '7',
        name: 'Gold Bracelet',
        price: 1940,
        favorite: false,
        stars: 4,
        imageUrl: 'accessory3.jpg',
        tags: ['Accessories'],
    },
    {
        id: '8',
        name: 'Silver Set',
        price: 1253,
        favorite: false,
        stars: 4.5,
        imageUrl: 'accessory4.jpg',
        tags: ['Accessories'],
    },
    {
        id: '9',
        name: 'Leather and Silver Bracelet',
        price: 254,
        favorite: false,
        stars: 4.5,
        imageUrl: 'accessory5.jpg',
        tags: ['Accessories'],
    },
    {
        id: '10',
        name: 'Traditional purse',
        price: 178,
        favorite: false,
        stars: 4.5,
        imageUrl: 'accessory6.jpg',
        tags: ['Accessories'],
    },

    {
        id: '11',
        name: 'Carpet',
        price: 495,
        favorite: false,
        stars: 4.5,
        imageUrl: 'carpet.jpg',
        tags: ['Decoration'],
    },
    {
        id: '12',
        name: 'Decor1',
        price: 123,
        favorite: false,
        stars: 4.5,
        imageUrl: 'decor1.jpg',
        tags: ['Decoration'],
    },
    {
        id: '13',
        name: 'Decor2',
        price: 98,
        favorite: false,
        stars: 4.5,
        imageUrl: 'decor2.jpg',
        tags: ['Decoration'],
    },
    {
        id: '14',
        name: 'Decor3',
        price: 153,
        favorite: false,
        stars: 4.5,
        imageUrl: 'decor3.jpg',
        tags: ['Decoration'],
    },
    {
        id: '15',
        name: 'Decor4',
        price: 49,
        favorite: false,
        stars: 4.5,
        imageUrl: 'decor4.jpg',
        tags: ['Decoration'],
    },


];

export const sample_tags = [
    { name: 'All', count: 15 },
    { name: 'Clothes', count: 4 },
    { name: 'Accessories', count: 6 },
    { name: 'Decoration', count: 5 },

];

export const sample_users = [
    {
        id: 1,
        name: 'John Doe',
        email: 'john@gmail.com',
        password: '12345',
        address: 'Toronto On',
        isAdmin: false,
    },
    {
        id: 2,
        name: 'Jane Doe',
        email: 'jane@gmail.com',
        password: '12345',
        address: 'Shanghai',
        isAdmin: true,
    },
];
